version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    command:
      ["npx", "serve", "-s", "build", "&&", "node", "getLastDayWorkItems.js"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
