CREATE TABLE IF NOT EXISTS Actions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  jobId INT NOT NULL,
  description VARCHAR(255), 
  created TIMESTAMP DEFAULT NOW(),
  CONSTRAINT `fk_jobId`
    FOREIGN KEY (jobId) REFERENCES Jobs (id)
    ON DELETE CASCADE
);